import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/app/components/Providers'
import AppNavbar from '@/app/components/AppNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Geração 666',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <AppNavbar />

          <div className="xl:container mx-auto">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
