import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/app/components/Providers'
import AppNavbar from '@/app/components/AppNavbar'
import AppFooter from './components/AppFooter'
import classNames from 'classnames'
import { KBarProvider } from 'kbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Geração 666',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={classNames('flex', 'flex-col', 'min-h-screen', inter.className)}>
        <Providers>
          <AppNavbar />

          <div className="container mx-auto px-32">
            {children}
          </div>

          <AppFooter />
        </Providers>
      </body>
    </html>
  )
}
